Tenutech/Shoprite

app/Http/Controllers/SettingsController.php, app/Http/Controllers/ShortlistController.php, database/migrations/2024_08_12_162055_add_shortlist_limits_to_settings_table.php, public/build/js/pages/shortlist.init.js, resources/views/admin/settings.blade.php, resources/views/manager/shortlist.blade.php
- Added new migration to add settings for min and max shortlist number
- Added validation in shortlist.js to use max and min settings values
=> SS-16 | Add shorlist number validation and settings

app/Http/Controllers/ShortlistController.php, resources/views/job-overview.blade.php
This PR removes the 'Advertise' option from the UI and updates the ShortlistController.
=> Remove 'Advertise' to advertise to Social media platforms

resources/views/job-overview.blade.php
This PR removes the 'Contact Us' section from the job detail page.
=> SS-13 | Remove contact us from job detail page

resources/views/manager/home.blade.php
This PR removes the recent activity and all details from the manager dashboard on the right.
=> SS-14 | Remove recent activity and details from manager dashboard

resources/views/manager/shortlist.blade.php
This PR renames 'Education' to 'Minimum Qualification' in the relevant sections.
=> SS-20 | Rename education to minimum qualification

app/Http/Controllers/ApplicantProfileController.php
This PR removes the top applicants block from the relevant sections.
=> SS-23 | Remove top applicants block

app/Http/Controllers/ApplicantProfileController.php, resources/views/layouts/sidebar.blade.php, resources/views/layouts/topbar.blade.php, resources/views/manager/applicant-profile.blade.php
Remove from Line Manager display: chat functionality & history of chats. Remove the messaging tab (will be visible to the Administrators).
=> SS-24 | Remove chat functionality from Line Manager display

resources/views/admin/user-profile.blade.php, resources/views/profile.blade.php
This PR removes the 'My Assessments' section from the Applicants page.
=> SS-46 | Remove 'My Assessments' from Applicants page

app/Http/Controllers/VacancyController.php, app/Models/Vacancy.php, public/build/js/pages/vacancy.init.js, resources/views/manager/vacancy.blade.php
This PR switches off Step 4, which is only being piloted to external candidates.
=> SS-7 | Switching off Step 4 (Only piloting to external candidates)

resources/views/manager/applicant-profile.blade.php
This PR removes the assessments tab from the line manager display.
=> SS-26 | Remove the assessments tab from the line manager display

resources/views/application.blade.php, resources/views/home.blade.php
This PR removes the edit function for applicants after they have submitted their details.
=> SS-52 | Remove edit function for applicants after submission details

app/Exports/EmailExport.php, app/Http/Controllers/EmailController.php, app/Models/EmailTemplate.php, database/migrations/2024_08_30_104117_add_role_id_to_email_templates_table.php, public/build/js/pages/email.init.js, resources/views/admin/email.blade.php
Categorize notifications, i.e Manager, Applicant.
=> SS-56 | Categorize Email Templates

resources/views/manager/applicant-profile.blade.php
Remove the documents tab from the line manager's display.
=> SS-27 | Remove documents tab from the line manager display

public/build/js/pages/vacancies.init.js
Park the advertising block in the vacancies page.
=> SS-44 | Park advertising block

app/Http/Controllers/InterviewController.php, app/Http/Controllers/ShortlistController.php, public/build/js/pages/shortlist.init.js, resources/views/manager/shortlist.blade.php
This PR implements the following changes:
- Park short list type & applicant type.
- Default shortlist type & applicant type to 'any'.
- Encrypted vacancyID.
This also solves SS-18.
=> SS-17 | Park short list type & applicant type, default shortlist type & applicant type to 'any'

app/Http/Controllers/ProfileSettingsController.php, app/Notifications/NotifyEmail.php, resources/views/profile-settings.blade.php
This PR turns off all notifications to managers.
=> Turn off all notifications to manager

app/Http/Controllers/PositionsController.php
This PR hides the 'Any' and 'Other' options from position types.
=> SS-54 | Hide 'ANY' and 'Other' from position types

app/Http/Controllers/ManagerController.php, app/Models/Vacancy.php, public/build/js/pages/manager.init.js, resources/views/manager/home.blade.php, resources/views/manager/partials/shortlist-modal.blade.php
This PR introduces a popup modal for un-actioned shortlists, prompting users to schedule interviews when a shortlist has been created but no interviews have been scheduled.
=> SS-48 | Popup for Un-Actioned Shortlist

app/Http/Controllers/ShortlistController.php
This PR adds functionality to filter applicants based on brand_id, ensuring that applicants meet the required criteria for the vacancy's store brand.
=> SS-19 | Add brand filtering for applicants

app/Http/Controllers/AdminController.php, app/Http/Controllers/RPPController.php, app/Services/DataService/ApplicantDataService.php, config/constants.php, resources/views/admin/home.blade.php, resources/views/rpp/home.blade.php
* Added drop off by question
* Added completetion and drop off by region
=> SS-91 | Application completion

app/Exports/ApplicantsExport.php, app/Exports/StoresOverTimeExport.php, app/Http/Controllers/Reports/ApplicantsReportController.php, app/Http/Controllers/Reports/StoresController.php, app/Http/Controllers/ShortlistController.php, app/Jobs/SendQueryEmailNotification.php, app/Jobs/SendQueryToJira.php, app/Services/ChatService.php, app/Services/DataService/ApplicantDataService.php, app/Services/DataService/Reports/ApplicantsReportDataService.php, app/Services/DataService/Reports/StoreDataService.php, app/Services/DataService/VacancyDataService.php, phpcs.xml, public/build/js/pages/reports/stores.init.js, resources/views/admin/reports/stores/index.blade.php, resources/views/admin/reports/stores/partials/filters.blade.php, resources/views/layouts/customizer.blade.php, routes/web.php
* Added new stores controller
* Added new reports routes
* Added new reports template
=> SS-165 | Stores Reports page

app/Http/Controllers/Reports/ApplicantsReportController.php, app/Jobs/GenerateApplicantsReportJob.php, app/Jobs/SendQueryEmailNotification.php, config/mail.php, public/build/js/pages/applicants-report.init.js
This PR implements the necessary updates and changes for branch SS-169.
=> SS-169 | Implemented required changes

app/Http/Controllers/ShortlistController.php, resources/views/manager/shortlist.blade.php
Add functionality to filter shortlisted candidates by age for more targeted selection.
=> SS-179 | Enable Filtering of Shortlist by Age

app/Exports/VacanciesExport.php
Ensure each SAP position number is listed on a separate line in the Vacancies report for better readability.
=> SS-176 | Display Each SAP Position Number on a Separate Line in Vacancies Report

app/Http/Controllers/AdminController.php, app/Http/Controllers/ApplicantsTableController.php, app/Http/Controllers/DataController.php, app/Http/Controllers/Reports/ApplicantsReportController.php, app/Services/DataService/ApplicantProximityService.php, app/Services/DataService/VacancyDataService.php, public/build/js/pages/admin.init.js, public/build/js/pages/applicants-report.init.js, public/build/js/pages/applicants-table.init.js, resources/views/admin/applicants-table.blade.php, resources/views/admin/home.blade.php, resources/views/dpp/home.blade.php, resources/views/dtdp/home.blade.php, resources/views/manager/home.blade.php, resources/views/reports/applicants.blade.php, resources/views/rpp/home.blade.php, routes/web.php, tests/Feature/Services/ApplicantProximitySerivceTest.php
This PR addresses performance issues in the applicants table by implementing server-side pagination and optimizing the rendering process. Key changes include:
- **Server-Side Pagination**: Loading applicant data in chunks.
- **Query Optimization**: Fetching only necessary fields to reduce memory usage.
- **JavaScript Adjustments**: Ensuring List.js works seamlessly with paginated data.
- **Performance Testing**: Verifying the solution with large datasets.
- Server-side pagination for the applicants table.
- List.js functionality (search, filter, sort) preserved across pages.
- PHP memory usage does not exceed limits during table rendering.
- Smooth user experience with no delays during navigation.
- Tested with a dataset of 50,000 records.
- Verified backward compatibility for search, …
=> SS-183 | Add Pagination and Optimize Applicant List Rendering

app/Http/Controllers/AdminController.php, app/Http/Controllers/DataController.php, app/Services/DataService/ApplicantProximityService.php, app/Services/DataService/VacancyDataService.php, public/build/js/pages/admin.init.js, resources/views/admin/home.blade.php, resources/views/dpp/home.blade.php, resources/views/dtdp/home.blade.php, resources/views/manager/home.blade.php, resources/views/rpp/home.blade.php, routes/web.php
Enable tooltips or hover descriptions for dashboard fields to provide users with additional context when hovering over any field.
=> SS-172 | Add Description Display for Dashboard Fields

public/build/js/pages/applicants-report.init.js, public/build/js/pages/vacancies-report.init.js, resources/views/admin/applicant-approvals.blade.php, resources/views/admin/applicants-table.blade.php, resources/views/admin/home.blade.php, resources/views/admin/user-profile.blade.php, resources/views/calendar.blade.php, resources/views/layouts/sidebar.blade.php, resources/views/manager/applicant-profile.blade.php, resources/views/manager/applicants.blade.php, resources/views/manager/partials/noshow-modal.blade.php, resources/views/manager/shortlist.blade.php, resources/views/manager/vacancy.blade.php, resources/views/profile.blade.php, resources/views/reports/applicants.blade.php
Resolve the issue where selection buttons at the top-right corner of Vacancy statistics are non-functional.
=> SS-175 | Fix Selection Buttons for Vacancy Statistics Filters

app/Http/Controllers/ProfileSettingsController.php, app/Mail/VerifyEmailUpdate.php, app/Models/User.php, database/migrations/2025_02_03_140141_add_email_verification_token_to_users.php, public/build/js/pages/profile-settings.init.js, resources/views/profile-settings.blade.php, resources/views/vendor/notifications/verify-email-update.blade.php, routes/web.php
Currently, users can update their profile information without any additional security verification. This needs to change so that users must first verify their email before they can edit any details on their profile.
=> SS-189 | Require Email Verification Before Profile Updates

app/Http/Controllers/ProfileSettingsController.php, app/Mail/VerifyEmailUpdate.php, app/Models/User.php, database/migrations/2025_02_03_140141_add_email_verification_token_to_users.php, public/build/js/pages/profile-settings.init.js, resources/views/profile-settings.blade.php, resources/views/vendor/notifications/verify-email-update.blade.php, routes/web.php
We need to create a scheduled function in Laravel that will mark vacancies as 'Deleted' if they meet specific criteria. This function should run daily at 2 AM and adhere to the vacancy_posting_duration setting.
=> SS-187 | Automatically Mark Vacancies as Deleted After Expiry
